### ISSUE TITLE
Warning: apt-key output should not be parsed (stdout is not a terminal)

### ISSUE THREAD

**Issue by JaneConan** [AutumnWhj/ChatGPT-wechat-bot#33]
![image](https://user-images.githubusercontent.com/26090153/206752707-6abb410d-2586-4967-a47b-fe6f64545dd3.png)

**Comment by Sisyphean-a** [comment]
我也遇到了这个问题，你有成功解决吗？

**Comment by AutumnWhj** [comment]
@JaneConan @Sisyphean-a 能提供一下复现步骤吗？

**Comment by Sisyphean-a** [comment]
@AutumnWhj 
不知道哪些信息对你有用

-- 系统版本
Ubuntu 22.04 LTS

-- Docker版本
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        100c70180f
 Built:             Thu Sep 22 06:21:41 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

-- 步骤
git clone https://github.com/AutumnWhj/ChatGPT-wechat-bot.git
cd ChatGPT-wechat-bot/
docker build --pull --rm -f "Dockerfile" -t wechatbot:latest "."

我在遇到这个警告之前，前面还有一个警告：
debconf: delaying package configuration, since apt-utils is not installed
![屏幕截图](https://user-images.githubusercontent.com/59257340/206829455-c4c453b4-7f54-428b-9a9a-9d5f7e563b47.png)

**Comment by AutumnWhj** [comment]
@Sisyphean-a  尝试这段代码加进去试试 `# Suppress an apt-key warning about standard out not being a terminal. Use in this script is safe.
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn`

**Comment by AutumnWhj** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/39156049/206831494-e4d6830a-093b-4b8d-a131-f4887359d33c.png">

**Comment by AutumnWhj** [comment]
@Sisyphean-a  我搞了个Ubuntu的服务器，docker版本跟你对齐了 `Docker version 20.10.17, build 100c701`，没发现有问题。
